import kattenSpike from "/assets/kattenSpike.jpg";
import sköldpaddaCleo from "/assets/sköldpaddaCleo.jpg";
import svampBurt from "/assets/svampBurt.jpg";
import enhörningRio from "/assets/enhörningRio.jpg";
import enhörningStar from "/assets/enhörningStar.jpg";
import larvenHugo from "/assets/larvenHugo.jpg";
import nissenEli from "/assets/nissenEli.jpg";
import axolotlFrans from "/assets/axolotlFrans.jpg";
import babyDragon from "/assets/babyDragon.jpg";
import babyGoblin from "/assets/babyGoblin.jpg";
import sköldpaddanBubb from "/assets/sköldpaddanBubb.jpg";
import svampenDeadly from "/assets/svampenDeadly.jpg";

const vasenDetails = [
  {
    key: "eli",
    id: "eli",
    heading: "Nissen Eli",
    name: "Eli",
    imgURL: nissenEli,
    price: "179 sek",
    size: "20cm",
    yarn: "Flerfärgad",
    eyecolor: "Gröna",
    stuffing: "Bomull",
    extra: "Barnsäkra ögon",
    category: "Jul",
  },
  {
    key: "frans",
    id: "frans",
    heading: "Axolotl Frans",
    name: "Frans",
    imgURL: axolotlFrans,
    price: "179 sek",
    size: "20cm",
    yarn: "Flerfärgad",
    eyecolor: "Gröna",
    stuffing: "Bomull",
    extra: "Barnsäkra ögon",
  },
  {
    key: "saga",
    id: "saga",
    heading: "Draken Saga",
    name: "Saga",
    imgURL: babyDragon,
    price: "200 sek",
    size: "30cm",
    yarn: "Flerfärgad",
    eyecolor: "Blåa",
    stuffing: "Bomull",
    extra: "Barnsäkra ögon",
  },
  {
    key: "missy",
    id: "missy",
    heading: "Goblin Missy",
    name: "Missy",
    imgURL: babyGoblin,
    price: "150 sek",
    size: "15cm",
    yarn: "Flerfärgad",
    eyecolor: "Gröna",
    stuffing: "Bomull",
    extra: "Barnsäkra ögon",
  },
  {
    key: "bubb",
    id: "bubb",
    heading: "Sköldpaddan Bubb",
    name: "Bubb",
    imgURL: sköldpaddanBubb,
    price: "179 sek",
    size: "20cm",
    yarn: "Flerfärgad",
    eyecolor: "Lila",
    stuffing: "Bomull",
    extra: "Barnsäkra ögon",
    category: "Midsommar",
  },
  {
    key: "deadly",
    id: "deadly",
    heading: "Svampen Deadly",
    name: "Deadly",
    imgURL: svampenDeadly,
    price: "150 sek",
    size: "20cm",
    yarn: "Vit / Svart",
    eyecolor: "Svarta",
    stuffing: "Bomull",
    extra: "Barnsäkra ögon",
    category: "Halloween",
  },
  {
    key: "spike",
    id: "spike",
    heading: "Katten Spike",
    name: "Spike",
    imgURL: kattenSpike,
    price: "150 sek",
    size: "15cm",
    yarn: "Svart",
    eyecolor: "Gröna",
    stuffing: "Bomull",
    extra: "Barnsäkra ögon",
    category: "Halloween",
  },
  {
    key: "cleo",
    id: "cleo",
    heading: "Sköldpaddan Cleo",
    name: "Cleo",
    imgURL: sköldpaddaCleo,
    price: "250 sek",
    size: ["40cm", "stor"],
    yarn: "Vit / Grön",
    eyecolor: "Gröna",
    stuffing: "Bomull",
    extra: "Barnsäkra ögon",
  },
  {
    key: "burt",
    id: "burt",
    heading: "Svampen Burt",
    name: "Burt",
    imgURL: svampBurt,
    price: "100 sek",
    size: "20cm",
    yarn: "Vit / Blå",
    eyecolor: "Blåa",
    stuffing: "Bomull",
    extra: "Barnsäkra ögon",
  },
  {
    key: "rio",
    id: "rio",
    heading: "Enhörningen Rio",
    name: "Rio",
    imgURL: enhörningRio,
    price: "200 sek",
    size: ["30cm", "stor"],
    yarn: "Vit / Flerfärgad",
    eyecolor: "Lila",
    stuffing: "Bomull",
    extra: "Barnsäkra ögon",
  },
  {
    key: "hugo",
    id: "hugo",
    heading: "Larven Hugo",
    name: "Hugo",
    imgURL: larvenHugo,
    price: "100 sek",
    size: "15cm",
    yarn: "Flerfärgad",
    eyecolor: "Lila",
    stuffing: "Bomull",
    extra: "Barnsäkra ögon",
  },
  {
    key: "star",
    id: "star",
    heading: "Enhörningen Star",
    name: "Star",
    imgURL: enhörningStar,
    price: "150 sek",
    size: "20cm",
    yarn: "Vit / Flerfärgad",
    eyecolor: "Lila",
    stuffing: "Bomull",
    extra: "Barnsäkra ögon",
  },
];

export default vasenDetails;
